services:
  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: lead_scoring_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # AI Lead Scoring Engine API
  lead_scoring_api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.simple
    container_name: lead_scoring_api
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      REDIS_URL: redis://redis:6379/0
      API_HOST: 0.0.0.0
      API_PORT: 8000
      PYTHONPATH: /app
    volumes:
      - ../models:/app/models
      - ../config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  default:
    driver: bridge
