apiVersion: apps/v1
kind: Deployment
metadata:
  name: lead-scoring-engine
  labels:
    app: lead-scoring-engine
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lead-scoring-engine
  template:
    metadata:
      labels:
        app: lead-scoring-engine
    spec:
      containers:
      - name: lead-scoring-engine
        image: lead-scoring-engine:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: url
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api-key
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: lead-scoring-service
spec:
  selector:
    app: lead-scoring-engine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lead-scoring-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lead-scoring-engine
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAaG9zdDo1NDMyL2RhdGFiYXNl # base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  url: cmVkaXM6Ly9ob3N0OjYzNzk= # base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-secret
type: Opaque
data:
  api-key: c2stWW91ck9wZW5BSUFQSUtleQ== # base64 encoded
