global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'lead-scoring-api'
    static_configs:
      - targets: ['lead_scoring_api:8000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'lead-scoring-monitoring'
    static_configs:
      - targets: ['monitoring:8001']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Define alerting rules
rule_files:
  - "alert_rules.yml"
